fix default_lift_data
broadinstitute/gnomad_methods pull request #270
Opened 2020-11-02 05:42 UTC by mkanai

The current `default_lift_data` doesn't work since `new_locus` is set as `new_locus=lifted_over_locus.result` in `liftover_expr` as below. This PR fixes this error.

https://github.com/broadinstitute/gnomad_methods/blob/ef0fbf3b78ee675b5a94c0673fc28bf6a0960e9c/gnomad/utils/liftover.py#L95-L103

2020-11-02 14:49 UTC, ch-kr requested changes
thanks for catching this! LGTM.

I have two small comments -- could you reformat with black and add an entry to the changelog noting the fix?

2020-11-02 14:56 UTC, ch-kr commented
ah sorry just saw this https://github.com/broadinstitute/gnomad_methods/pull/269

2020-11-02 16:10 UTC, mkanai commented
Thanks Katherine! I added the changelog.

2020-11-02 16:10 UTC, ch-kr approved these changes

2020-11-16 15:58 UTC, nawatts commented
Hi @mkanai. The master branch has been repaired. If you update your branch, Pylint and documentation checks should run now.

2020-11-16 16:44 UTC, mkanai commented
@nawatts thanks! I updated and it seems all checks have passed.

2020-11-16 16:51 UTC, merged