Added util to call parallel_file_exists
broadinstitute/gnomad_methods pull request #398
Opened 2021-08-04 14:59 UTC by ch-kr

2021-08-04 18:05 UTC, nawatts commented
Since we generally don't use async functions in pipelines, should the synchronous wrapper get the `parallel_file_exists` name instead?

```python
async def parallel_file_exists_async(fnames):
    ...

def parallel_file_exists(fnames):
    return asyncio.get_event_loop().run_until_complete(parallel_file_exists_async(fnames))
```

2021-08-05 15:01 UTC, bw2 requested changes

2021-08-05 15:01 UTC, bw2 commented on gnomad/utils/file_utils.py
> +    :param fnames: List of file names to check.
Would add a sentence on whether these can be local or gs:// file paths (or both). 
Also maybe rename fnames => fpaths?

2021-08-05 16:19 UTC, bw2 approved these changes

2021-08-05 16:22 UTC, bw2 commented on gnomad/utils/file_utils.py
> +    :param parallelism: Integer that sets parallelism of file existence checking task. Default is 750.
Just noticed the function doesn't have a parallelism arg..

2021-08-05 18:03 UTC, merged