add vds resource
broadinstitute/gnomad_methods pull request #423
Opened 2021-11-18 14:28 UTC by klaricch

2021-11-29 16:26 UTC, jkgoodrich requested changes
A few small things

2021-11-29 16:26 UTC, jkgoodrich commented on gnomad/resources/resource_utils.py
> +        Read and return the Hail VariantDataset resource.
```suggestion
        Read and return the Hail VariantDataset resource.
        
```

2021-11-29 16:26 UTC, jkgoodrich commented on gnomad/resources/resource_utils.py
> +            return hl.read_vds(self.path)
I think this is actually:
```suggestion
            return hl.vds.read_vds(self.path)
```

2021-11-29 16:26 UTC, jkgoodrich commented on gnomad/resources/resource_utils.py
> +        Import the VariantDataset resource using its import_func and writes it in its path.
```suggestion
        Import the VariantDataset resource using its import_func and writes it in its path.
        
        
```

2021-11-29 16:26 UTC, jkgoodrich commented on gnomad/resources/resource_utils.py
> +    Versioned VariantDataset resource.
```suggestion
    Versioned VariantDataset resource.
    
```

2021-11-29 16:26 UTC, jkgoodrich commented on gnomad/resources/resource_utils.py
> +    :param default_version: The default version of this VariantDataset resource (must to be in the `versions` dict)
```suggestion
    :param default_version: The default version of this VariantDataset resource (must to be in the `versions` dict)
    
```

2021-11-29 16:26 UTC, jkgoodrich commented
Also, I think you need to run Black

2021-11-30 04:17 UTC, jkgoodrich approved these changes
LGTM

2021-11-30 14:59 UTC, nawatts commented
The [Pylint failure](https://github.com/broadinstitute/gnomad_methods/runs/4357803799?check_suite_focus=true) is resolved in #425.

2021-12-01 16:44 UTC, merged