Modified annotate_sex()
broadinstitute/gnomad_methods pull request #427
Opened 2021-12-14 22:09 UTC by wlu04

2021-12-15 16:26 UTC, jkgoodrich requested changes
Some questions, but it's very possible I'm not following because I haven't worked with the VDS format as long as you. Thanks for putting in this PR!

2021-12-15 16:26 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +    if is_vds:
I think I'm not fully following this. For a VDS at this point `mt` is just the split biallelic variant data MT so `filter_intervals` should work fine on it right? And this only keeps the `mtds.variant_data`

2021-12-15 16:26 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +        if is_vds:
Is this needed? If only keeping `mtds.variant_data` and not using `mtds` after this, I don't think `hl.vds.filter_variants` is needed

2021-12-15 17:35 UTC, wlu04 commented on gnomad/sample_qc/pipeline.py
> +        mtds = hl.vds.split_multi(mtds, filter_changed_loci=True)
This is right, they work equivalently on `mtds.variant_data`. Sorry about that. And in this case, do we want to add a warning or something about using `filter_chaged_loci`  before loading the data?

2021-12-15 19:07 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +        mtds = hl.vds.split_multi(mtds, filter_changed_loci=True)
No, I think it's fine without it, it's outside the scope of the function and the MT doesn't even need to be split before using it

2021-12-15 19:15 UTC, jkgoodrich requested changes
This is close to ready, just a couple more comments (minus the addition of `hl.vds.impute_sex_chromosome_ploidy` to Hail for tests to pass)

2021-12-15 19:15 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +    :param reference_genome: Reference genome used for constructing interval list. Default: 'GRCh38'
I wonder if we should just infer this from the MT? example: https://github.com/broadinstitute/gnomad_methods/blob/978b57762108d6ccbe979ed7a867ffe361d146e6/gnomad/utils/filtering.py#L133

2021-12-15 19:15 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +                "excluded_intervals is not used when imputing sex chromosome ploidy for VDS"
```suggestion
                "The use of the parameter excluded_intervals is currently not implemented for imputing sex chromosome ploidy on a VDS"
```

2021-12-16 19:36 UTC, jkgoodrich approved these changes
two more tiny suggestions, and it looks like `hl.vds.impute_sex_chromosome_ploidy` might now be in Hail, so a recommit should hopefully fix that error

2021-12-16 19:36 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +        - chr20_mean_dp/autosomal_mean_dp (float32): Sample's mean coverage over chromosome 20.
```suggestion
        - {normalization_contig}_mean_dp (float32): Sample's mean coverage over the specified `normalization_contig`.
```

2021-12-16 19:36 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +                "The use of the parameter excluded_intervals is currently not implemented for imputing sex chromosome ploidy on a VDS"
```suggestion
                "The use of the parameter 'excluded_intervals' is currently not implemented for imputing sex chromosome ploidy on a VDS!"
```

2021-12-16 19:36 UTC, jkgoodrich commented on gnomad/sample_qc/pipeline.py
> +            }
```suggestion
                "autosomal_mean_dp": f"{normalization_contig}_mean_dp",
            }
```

2021-12-17 16:56 UTC, jkgoodrich approved these changes
LGTM

2022-01-03 15:31 UTC, jkgoodrich approved these changes

2022-01-03 15:31 UTC, merged