Allow any frequency groupings
broadinstitute/gnomad_methods pull request #545
Opened 2023-05-25 20:03 UTC by mike-w-wilson

This PR expands on the utility of `additional_strata_expr` by allowing the user to pass a list of dictionaries where each dictionary will be grouped together. This relies on the user to define the specific groupings for freq calculations, e.g. [{'pop': pop_expr}, {'platform': platform_expr, 'pop': pop_expr}, {'sample_age_bin': sample_age_bin_expr}]. I think this could eventually be used for all aggregations and clean this function up quite a bit.  I kept the ability to pass a single dictionary but have removed the additonal_strata_groupings_expr as this is a cleaner and more flexible implementation.

2023-06-08 19:43 UTC, KoalaQin requested changes

2023-06-09 12:11 UTC, mike-w-wilson commented
@KoalaQin , wI see you marked the review as changes requested but what changes would you like to see?

2023-06-09 13:54 UTC, KoalaQin commented
@mike-w-wilson Hi, Mike, sorry, I wasn't clear, I was thinking maybe you can change the doc for "additional_strata_expr", because you used `pop` and `platform` in your example, but we are going to do this on `gatk_version` and `sample_age_bin` this time, just for my testing convenience.

2023-06-09 14:05 UTC, mike-w-wilson commented
Since this is the gnomad_methods repo, we want the functions to be as general as possible. Pop and platform are something we mention in the repo so I figured it makes sense to use this as an example where gatk_version is not. All of that logic, around gatk_version will live in the gnomad_qc repo.

2023-06-09 14:06 UTC, KoalaQin approved these changes

2023-06-14 13:52 UTC, merged