add optional ab_expr to qual_hists
broadinstitute/gnomad_methods pull request #555
Opened 2023-06-22 14:12 UTC by mike-w-wilson

This adds an `ab_expr` to  the qual_hists_expr. Currenlt the ab hists rely on AD which is expensive to densify as an array expression of ints. This would allow us to pass a single float expr while maintaining the original AD functionality.

2023-06-22 14:12 UTC, mike-w-wilson commented on gnomad/utils/annotations.py
> +        {"non_par": t.locus.in_x_nonpar() | t.locus.in_y_nonpar()} if non_par else {}
```suggestion
        {"non_par": (t.locus.in_x_nonpar() | t.locus.in_y_nonpar())} if non_par else {}
```

2023-06-23 17:15 UTC, jkgoodrich requested changes
One question and add a logger

2023-06-23 17:15 UTC, jkgoodrich commented on gnomad/utils/annotations.py
> +        if ab_expr is not None:
Just add a logger stating which expression is being used

2023-06-23 17:15 UTC, jkgoodrich commented on gnomad/utils/annotations.py
> +            qual_hists["ab_hist_all"] = hl.agg.filter(
Should this still be `ab_hist_alt`?

2023-06-23 17:15 UTC, jkgoodrich commented on gnomad/utils/annotations.py
> +            qual_hists["ab_hist_all"] = hl.agg.filter(
Same question

2023-06-23 18:48 UTC, jkgoodrich approved these changes
LGTM!

2023-06-23 19:23 UTC, merged