Update ancestry population names in gks method to always use v4
broadinstitute/gnomad_methods pull request #687
Opened 2024-03-27 22:24 UTC by theferrit32

Annotating v4 genomes now fails since the v4 genomes table uses ancestry population names from v4. This fixes that.

2024-03-28 15:20 UTC, klaricch commented
can you clarify the issue? does it involve the change from oth -> remaining?
just switching to always use POPS v4 isn't suitable as currently written because it would drop 'ami' from genomes

2024-03-28 19:20 UTC, klaricch requested changes
https://github.com/broadinstitute/gnomad_methods/pull/687#issuecomment-2025483805

2024-04-03 20:29 UTC, theferrit32 commented
Yes @klaricch this was because some of the v3 genomes population labels are no longer in the v4 genomes so it was getting a KeyError. I guess this change is too imprecise though because it might miss some that are there. Do you have an idea of how to better keep the population labels we reference in sync with what's in the tables?

Should another set of labels be added? If v3 genomes and v4 genomes and v4 exomes don't all have the same ancestry groups then do we need 3 sets of keys instead of just the two v3 and v4 in hardcoded in there now? Or can we infer the groups from whatever's in the table?

2024-04-11 13:40 UTC, klaricch commented
I think the issue you were seeing should be resolved with this PR (https://github.com/broadinstitute/gnomad_methods/pull/690), but if not, let me know

2024-04-11 13:40 UTC, closed without merging

2024-04-11 18:09 UTC, theferrit32 commented
Thank you @klaricch !