Update POPS constant to contain a dictionary of both exomes and genomes
broadinstitute/gnomad_methods pull request #690
Opened 2024-04-09 18:58 UTC by klaricch

2024-04-09 19:48 UTC, mike-w-wilson requested changes
Just one small change and then this LGTM!

2024-04-09 20:27 UTC, klaricch commented on gnomad/resources/grch38/gnomad.py
>      "v3": ["afr", "ami", "amr", "asj", "eas", "fin", "nfe", "oth", "sas", "mid"],
ah good point

2024-04-10 18:11 UTC, mike-w-wilson approved these changes
Two small things then this looks good! Thanks for doing it!

2024-04-10 18:11 UTC, mike-w-wilson commented on gnomad/utils/release.py
> +    :param pops: List of sample global population names for gnomAD genomes. Default is POPS[CURRENT_MAJOR_RELEASE]["exomes"].
```suggestion
    :param pops: List of sample global population names for gnomAD data type. Default is POPS[CURRENT_MAJOR_RELEASE]["exomes"].
```

2024-04-10 18:11 UTC, mike-w-wilson commented on gnomad/utils/release.py
> +    :param pops: List of sample global population names for gnomAD genomes. Default is POPS[CURRENT_MAJOR_RELEASE]["exomes"].
```suggestion
    :param pops: List of sample global population names for gnomAD data type. Default is POPS[CURRENT_MAJOR_RELEASE]["exomes"].
```

2024-04-10 19:23 UTC, merged